-- Global options (can be set directly without vim.cmd)
vim.opt.expandtab = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.autoindent = true
vim.opt.copyindent = true
vim.opt.smartindent = true
vim.opt.filetype.indent = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.wrap = false
vim.g.mapleader = ' '  -- You can use ' ' for space or ',' for comma as your leader key
vim.opt.clipboard = "unnamedplus"
vim.o.foldcolumn = '1' -- '0' is not bad
vim.o.foldlevel = 99   -- Using ufo provider need a large value, feel free to decrease the value
vim.o.foldlevelstart = 99
vim.o.foldenable = true
vim.opt.splitright = true
vim.opt.shell = "/usr/bin/zsh" -- Ensure this points to your fish executable
vim.opt.shellcmdflag = "-c"    -- This is the default for most shells like fish, bash, zsh
vim.opt.termguicolors = true
vim.opt.encoding = "utf-8"
